#!/usr/bin/env python
"""This file provides a script to update post tags"""
from __future__ import print_function

from os import listdir
from os.path import dirname, join
from subprocess import check_call
from sys import exit as sys_exit

ROOT_DIR = dirname(__file__)
POSTS_DIR = join(ROOT_DIR, 'posts')

CURRENT_POSTS = [
    post.replace('.md.j2', '')
    for post in listdir(POSTS_DIR)
    if post.startswith('post')
]


def remove_tag(tag):
    """Remove the provided tag"""
    check_call(['git', 'tag', '-d', tag])


def add_tag(tag):
    """Add the provided tag"""
    check_call(['git', 'tag', tag])


def update_tag(tag):
    """Removes and re-adds the provided tag"""
    remove_tag(tag)
    add_tag(tag)


def update_all_posts():
    """Updates the tags for all existing posts"""
    for post in CURRENT_POSTS:
        update_tag(post)


def push_updates():
    """Force pushes tag updates"""
    check_call(['git', 'push', '--tags', '--force'])


def cli():
    """Updates the tags and pushes the update"""
    update_all_posts()
    push_updates()

if '__main__' == __name__:
    cli()
    sys_exit(0)
